jenkins:
  image: bzon/centos-adop-jenkins:0.3.0
  environment:
    AWS_REGION: "${AWS_REGION}"
    VPC_ID: "${VPC_ID}"
    KEY_PAIR: "${DEFAULT_KEY_PAIR}"
    DEFAULT_PUBLIC_SUBNET_ID: "${DEFAULT_PUBLIC_SUBNET_ID}"
    DEFAULT_PRIVATE_SUBNET_ID: "${DEFAULT_PRIVATE_SUBNET_ID}"
    DEFAULT_SECURITY_GROUP_ID: "${DEFAULT_SECURITY_GROUP_ID}"
    DEFAULT_RHEL_AMI: "${DEFAULT_RHEL_AMI}"
    PASSWORD_GITLAB: "${PASSWORD_GITLAB}"
    PUBLIC_IP: "${PUBLIC_IP}"
    LDAP_DOMAIN: "${LDAP_DOMAIN}"
 
jenkins-slave:
  image: bzon/adop-ansible-jenkins
  environment:
    SLAVE_EXECUTORS: "10"
    LDAP_DOMAIN: "${LDAP_DOMAIN}"
    SWARM_PASSWORD: "${PASSWORD_JENKINS}"
    PASSWORD_GITLAB: "${PASSWORD_GITLAB}"
    PUBLIC_IP: "${PUBLIC_IP}"
